---
# Variables Globales:
Variable_Vars_main: Algo
Nombre_Grupo: "314"
Division: "314-2"
cores_vm: "{{ ansible_processor_vcpus }}"
version_so: "{{ ansible_distribution }} {{ ansible_distribution_version }}"


LISTA_GRUPOS:
  - Nombre: Lautaro
    Apellido: Lotoski
    Rol:
      - R1
      - R2
  - Nombre: Tomas
    Apellido: Torres
    Rol:
      - R2
      - R5
  - Nombre: Leonel
    Apellido: Lopez
    Rol:
      - R3
      - R4


# R1: Nombre: <Tu-Nombre> Apellido: <Tu-Apellido>
# R2: Nombre: <Tu-Nombre> Apellido: <Tu-Apellido>
# R3: Nombre: <Tu-Nombre> Apellido: <Tu-Apellido>
# R4: Nombre: <Tu-Nombre> Apellido: <Tu-Apellido>
# R5: Nombre: <Tu-Nombre> Apellido: <Tu-Apellido>
# R6: Nombre: <Tu-Nombre> Apellido: <Tu-Apellido>

