---
# tasks file for roles/Instala-tools_314

- name: Instalar htop, tmux y speedtest-cli (usando package)
  become: yes
  ansible.builtin.package:
    name:
      - htop
      - tmux
      - speedtest-cli
    state: present
