---
# tasks file for roles/Instala-tools_314
- name: actualizar repos apt
  apt:
    update_cache: yes

- name: Instalar htop, tmux y speedtest-cli (usando package)
  become: yes
  ansible.builtin.package:
    name:
      - htop
      - tmux
      - speedtest-cli
    state: present
