---
- hosts: all
  # Variables Globales
  become: yes
  vars_files:
    - vars/main.yml

  tasks:
    - include_role:
        name: TP_INI
    
    - include_role:
        name: Instala-tools_314

    - include_role:
        name: Alta_Usuarios_314

    - include_role:
        name: Sudoers_314

    
    - name: "Otra tarea"
      debug:
        msg: "Despues de la ejecucion del rol"

