---
- hosts: 
#  - all
  - testing
  - produccion

  # Variables Globales
  vars_files:
    - vars/main.yml

  tasks:
    - include_role:
        name: TP_INI
    
    - include_role:
        name: Instala-tools_314
    
    - name: "Otra tarea"
      debug:
        msg: "Despues de la ejecucion del rol"

